# Generated by Django 3.0.8 on 2020-07-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0003_auto_20200727_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
