# Generated by Django 3.0.8 on 2020-07-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0004_auto_20200727_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='notice_file',
            field=models.FileField(upload_to='notices_pdf'),
        ),
    ]
