# Generated by Django 3.0.8 on 2020-07-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0005_auto_20200727_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=200)),
                ('exam_year', models.IntegerField()),
                ('result_file', models.FileField(upload_to='results_pdf')),
            ],
        ),
        migrations.AlterModelOptions(
            name='notices',
            options={'verbose_name_plural': 'Notices'},
        ),
    ]
