# Generated by Django 3.0.8 on 2020-07-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0006_auto_20200727_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nest.Notices')),
            ],
        ),
        migrations.AlterField(
            model_name='notices',
            name='notice_file',
            field=models.FileField(upload_to='uploads/notices_pdf'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_file',
            field=models.FileField(upload_to='uploads/results_pdf'),
        ),
    ]
