# Generated by Django 3.0.8 on 2020-07-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0007_auto_20200729_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
