# Generated by Django 3.0.8 on 2020-07-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0010_newsticker_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsticker',
            options={'verbose_name': 'Important News', 'verbose_name_plural': 'Important Newses'},
        ),
        migrations.AlterModelOptions(
            name='notices',
            options={'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.AlterField(
            model_name='notices',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
